version: 2
jobs:
  build:
    docker:
      - image: ishiko/gcc-ishiko-cpp:0.1.0
    steps:
      - run: 
          name: "Set DIPLODOCUSDB environment variable and create directory"
          command: mkdir /DiplodocusDB && echo 'export DIPLODOCUSDB="/DiplodocusDB"' >> $BASH_ENV
      - run:
          name: "Checkout DiplodocusDB/Core dependency"
          command: cd /DiplodocusDB && git clone https://github.com/DiplodocusDB/Core.git
      - checkout:
          path: /DiplodocusDB/TreeDB
      - run:
          name: "Build DiplodocusDB/Core dependency"
          command: cd /DiplodocusDB/Core/Makefiles/GNUmakefile && make
      - run:
          name: Build TreeDB/Core
          command: cd /DiplodocusDB/TreeDB/Core/Makefiles/GNUmakefile && make
      - run:
          name: Build TreeDB/Core tests
          command: cd /DiplodocusDB/TreeDB/Tests/Core/Makefiles/GNUmakefile && make
      - run:
          name: Run TreeDB/Core tests
          command: cd /DiplodocusDB/TreeDB/Tests/Core/Makefiles/GNUmakefile && ./DiplodocusTreeDBCoreTests
      - run:
          name: Build TreeDB/XMLTreeDB
          command: cd /DiplodocusDB/TreeDB/XMLTreeDB/Makefiles/GNUmakefile && make
      - run:
          name: Build TreeDB/XMLTreeDB tests
          command: cd /DiplodocusDB/TreeDB/Tests/XMLTreeDB/Makefiles/GNUmakefile && make
      - run:
          name: Run TreeDB/XMLTreeDB tests
          command: cd /DiplodocusDB/TreeDB/Tests/XMLTreeDB/Makefiles/GNUmakefile && ./DiplodocusXMLTreeDBTests
